BASE: "./mmm_median_inference.yaml"

# parameters for the inference engine
engine_params:
  median_kernel_size: 5

# simple object size/shape filters
filters:
  - { name: "remove_small_objects", min_size: 3000 }
  - { name: "remove_pancakes", min_span: 10 }